// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1iInYsqJSpVjgbJEl1GC-oZRKXZ0n3lA',
    appId: '1:565409367468:web:56eb0d413e9adfe58fe609',
    messagingSenderId: '565409367468',
    projectId: 'loooans-dev-stg',
    authDomain: 'loooans-dev-stg.firebaseapp.com',
    databaseURL: 'https://loooans-dev-stg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loooans-dev-stg.appspot.com',
    measurementId: 'G-DWEXQFQ26Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3rS-6l_nYDeI6qJEFZ4KP9AKPd14KG8w',
    appId: '1:565409367468:android:0fcc6ad66c7dd1b38fe609',
    messagingSenderId: '565409367468',
    projectId: 'loooans-dev-stg',
    databaseURL: 'https://loooans-dev-stg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loooans-dev-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX08UD0WTtFyp0-ovRNe5jlPIS6nc8JAs',
    appId: '1:565409367468:ios:6a8bf06a783fa9c08fe609',
    messagingSenderId: '565409367468',
    projectId: 'loooans-dev-stg',
    databaseURL: 'https://loooans-dev-stg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loooans-dev-stg.appspot.com',
    iosBundleId: 'com.loooans.app.dev',
  );
}
