// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATaPKWgNzIa9H1w_07VmSS42DPnHwxRZk',
    appId: '1:444559784514:web:be09bfc7525b4d7677cbdb',
    messagingSenderId: '444559784514',
    projectId: 'loooans-prod',
    authDomain: 'loooans-prod.firebaseapp.com',
    databaseURL: 'https://loooans-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loooans-prod.appspot.com',
    measurementId: 'G-ZPYS3RCP3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjg8SybrWeDTMNpG_DjffZLL6SAq8VvFU',
    appId: '1:444559784514:android:0c37a7d478cdc0ac77cbdb',
    messagingSenderId: '444559784514',
    projectId: 'loooans-prod',
    databaseURL: 'https://loooans-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loooans-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp3oN2XFZxbB2qrf7JXf7A2TKjea4BWpc',
    appId: '1:444559784514:ios:a2cfaff173b2b7a477cbdb',
    messagingSenderId: '444559784514',
    projectId: 'loooans-prod',
    databaseURL: 'https://loooans-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loooans-prod.appspot.com',
    iosBundleId: 'com.loooans.app',
  );

}